### ISSUE TITLE
gcp.cloudkms.v1.getKeyRingIamPolicy returning 404 response

### ISSUE THREAD

**Issue by ColeSiegelTR** [pulumi/pulumi-google-native#182]
Version: 0.6.0

```
const keyPolicy = gcp.cloudkms.v1.getKeyRingIamPolicy({
    keyRingId: config.kmsRing,
    location: config.region
});
```

Using the command line I am able to retrieve the policy:

`gcloud kms keyrings get-iam-policy projects/e4a9cc4f8271/locations/us/keyRings/dataproc-int/ --location us-east4`

## Steps to reproduce

Expected:
Get the keyring policy
Actual:
```
 error: Error: invocation of google-native:cloudkms/v1:getKeyRingIamPolicy returned an error: error sending request: googleapi: got HTTP response code 404 with body: <!DOCTYPE html>
    <html lang=en>
      <meta charset=utf-8>
      <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
      <title>Error 404 (Not Found)!!1</title>
      <style>
        *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
      </style>
      <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
      <p><b>404.</b> <ins>That’s an error.</ins>
      <p>The requested URL <code>/v1/projects/%7BprojectsId%7D/locations/us-east4/keyRings/projects/e4a9cc4f8271/locations/us/keyRings/dataproc-int/:getIamPolicy?alt=json</code> was not found on this server.  <ins>That’s all we know.</ins>
    
        at Object.callback (/Users/colesiegel/Documents/Workspaces/a206447_data-lake-common-infrastructure/pulumi/node_modules/@pulumi/pulumi/runtime/invoke.js:140:33)
        at Object.onReceiveStatus (/Users/colesiegel/Documents/Workspaces/a206447_data-lake-common-infrastructure/pulumi/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/Users/colesiegel/Documents/Workspaces/a206447_data-lake-common-infrastructure/pulumi/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/Users/colesiegel/Documents/Workspaces/a206447_data-lake-common-infrastructure/pulumi/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /Users/colesiegel/Documents/Workspaces/a206447_data-lake-common-infrastructure/pulumi/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (node:internal/process/task_queues:76:11)

```

**Comment by ColeSiegelTR** [comment]
Might be the same bug as https://github.com/pulumi/pulumi-google-native/issues/172

**Comment by mikhailshilkov** [comment]
Hi @ColeSiegelTR 

Do you have a config value `google-native:project` set in your stack? Do you get the same error if you set the `project: "your-project",` option in the function arguments explicitly?

**Comment by ColeSiegelTR** [comment]
Thanks @mikhailshilkov , I was missing that in my stack and thought it was similar bug as other case. Once i corrected that and the format for `keyRingId` it is working now.

**Comment by mikhailshilkov** [comment]
Great to hear your problem is solved now!

I'll reopen the issue and rename it to track improving the error message. We should clearly indicate what's missing there.
