### ISSUE TITLE
invocation of google-native:authorization:getClientToken returned an error

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-google-native#678]
### What happened?

invocation of google-native:authorization:getClientToken returned an error: error reading from server: EOF panic: runtime error: invalid memory address or nil pointer dereference

### Steps to reproduce

Create simple program:
```
% cat ~/scratch/gcp-get-token-nil-panic/index.ts 
import { getClientToken } from "@pulumi/google-native/authorization";

export = async () => {
    const token = getClientToken()
}
```

If you have not run `gcloud auth application-default login` you'll receive a go panic when `google-native:authorization:getClientToken` is invoked.

### Expected Behavior

Detail should be provided to user informing them they need to run `gcloud auth ....`

### Actual Behavior

Program panics

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by viveklak** [comment]
@phillipedwards could you make sure you are trying with a recent version of the provider SDK?

I just tried with v0.25.0 and I get the following instead:
```
Diagnostics:
  pulumi:pulumi:Stack (gnative-client-token-dev):
    error: Error: invocation of google-native:authorization:getClientToken returned an error: getting credentials: make sure you have:
    
         • configured the provider as per: https://www.pulumi.com/registry/packages/google-native/installation-configuration/
         • to use your gcloud credentials: run 'gcloud auth application-default login'
    
     original error: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
        at Object.callback (/Users/vivek/code/pulumi-google-native/sdk/nodejs/node_modules/@pulumi/runtime/invoke.ts:159:33)
        at Object.onReceiveStatus (/Users/vivek/code/pulumi-google-native/sdk/nodejs/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/Users/vivek/code/pulumi-google-native/sdk/nodejs/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/Users/vivek/code/pulumi-google-native/sdk/nodejs/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /Users/vivek/code/pulumi-google-native/sdk/nodejs/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**Comment by phillipedwards** [comment]
@viveklak Will certainly check it out. Thanks for the quick look.

**Comment by phillipedwards** [comment]
@viveklak I'm going to re-open this as I am still seeing the panic even when using `v0.26.0`.

```Diagnostics:
  pulumi:pulumi:Stack (gcp-native-bug-dev):
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe5b1a2]
    goroutine 47 [running]:
    github.com/pulumi/pulumi-google-native/provider/pkg/provider.(*googleCloudProvider).Invoke(0xc000180300, {0xc000513858?, 0x8b0b95?}, 0xc0030b2280)
        /home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/provider/provider.go:222 +0x602
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Invoke_Handler.func1({0x12cfd38, 0xc0030b0c30}, {0x1024500?, 0xc0030b2280})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.40.0/proto/go/provider.pb.go:3653 +0x7b
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x12cfd38, 0xc0030b09f0}, {0x1024500, 0xc0030b2280}, 0xc00037b820, 0xc003090bb8)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3f9
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Invoke_Handler({0x10a6ec0?, 0xc000180300}, {0x12cfd38, 0xc0030b09f0}, 0xc0003e6ee0, 0xc000399c20)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.40.0/proto/go/provider.pb.go:3655 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000108000, {0x12d5d20, 0xc00042b380}, 0xc002340480, 0xc002b245a0, 0x1ccad60, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:1301 +0xb2b
    google.golang.org/grpc.(*Server).handleStream(0xc000108000, {0x12d5d20, 0xc00042b380}, 0xc002340480, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:1642 +0xa2f
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:938 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:936 +0x28a
 
    error: Running program '/home/pedwards/repos/gcp-native-bug' failed with an unhandled exception:
    Error: invocation of google-native:authorization:getClientToken returned an error: error reading from server: read tcp 127.0.0.1:32876->127.0.0.1:45879: read: connection reset by peer
        at Object.callback (/home/pedwards/repos/gcp-native-bug/node_modules/@pulumi/runtime/invoke.ts:159:33)
        at Object.onReceiveStatus (/home/pedwards/repos/gcp-native-bug/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/home/pedwards/repos/gcp-native-bug/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/home/pedwards/repos/gcp-native-bug/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /home/pedwards/repos/gcp-native-bug/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

pulumi about
```
CLI
Version      3.40.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME           VERSION
google-native  0.26.0
nodejs         unknown

Host
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in nodejs: executable='/home/pedwards/.nvm/versions/node/v14.17.3/bin/node' version='v14.17.3'

Current Stack: dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/phillipedwards
User           phillipedwards
Organizations  phillipedwards

Dependencies:
NAME                   VERSION
@pulumi/google-native  0.26.0
@pulumi/pulumi         3.40.0
@types/node            14.18.29

Pulumi locates its logs in /tmp by default
```

**Comment by lblackstone** [comment]
I didn't try to reproduce the panic, but I tightened up the code so that this will fail gracefully with an error in case of problems.
